[tool.poetry]
name = "indexing"
version = "0.1.0"
description = ""
authors = ["sean.wedig@gmail.com <sean.wedig@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pymupdf = "^1.23.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
